sudo: false

language: node_js

matrix:
  include:
    - node_js: iojs-v1
    - node_js: iojs-v2
    - node_js: "0.10"
    - node_js: "0.12"

after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage"
notifications:
  email:
    - tormozz48@gmail.com
